sudo: required
language: python
services: docker
cache: pip
jdk: openjdk8

matrix:
  fast_finish: true
  include:
  - name: "Minimum Nextflow version, regular test suite with Unicycler assembly"
    env: NXF_VER='19.10.0' SUITE=test FLAGS= NXF_ANSI_LOG=0
    language: java
    jdk: openjdk8
  - name: "Latest Nextflow version, short read suite with Unicycler assembly"
    env: NXF_VER='' SUITE=test FLAGS= NXF_ANSI_LOG=0
  - name: "Latest Nextflow version, long read suite with Canu assembly"
    env: NXF_VER='' SUITE=test_long FLAGS='--assembler "canu"' NXF_ANSI_LOG=0
  - name: "Latest Nextflow version, long read suite with Miniasm assembly"
    env: NXF_VER='' SUITE=test_long FLAGS='--assembler "miniasm"' NXF_ANSI_LOG=0
  - name: "Latest Nextflow version, long read suite default" 
    env: NXF_VER='' SUITE=test_long FLAGS= NXF_ANSI_LOG=0
  - name: "Latest Nextflow version, test hybrid read approach"
    env: NXF_VER='' SUITE=test_hybrid FLAGS= NXF_ANSI_LOG=0
  - name: "Latest Nextflow version, test long reads with Nanopolish"
    env: NXF_VER='' SUITE=test_long FLAGS='--skip_nanopolish false' NXF_ANSI_LOG=0
  - name: "Lint the pipeline code"
    install:
      # Install nf-core/tools
      - pip install --upgrade pip
      - pip install nf-core
    script: nf-core lint ${TRAVIS_BUILD_DIR}
    python: '3.6'
    env: NXF_VER='19.10.0'
    jdk: openjdk8
  - name: "Lint the documentation"
    script: markdownlint ${TRAVIS_BUILD_DIR} -c ${TRAVIS_BUILD_DIR}/.github/markdownlint.yml
    python: '3.6'

before_install:
  # PRs to master are only ok if coming from dev branch
  - '[ $TRAVIS_PULL_REQUEST = "false" ] || [ $TRAVIS_BRANCH != "master" ] || ([ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ] && ([ $TRAVIS_PULL_REQUEST_BRANCH = "dev" ] || [ $TRAVIS_PULL_REQUEST_BRANCH = "patch" ]))'
  # Pull the docker image first so the test doesn't wait for this
  - docker pull nfcore/bacass:dev
  # Fake the tag locally so that the pipeline runs properly
  # Looks weird when this is :dev to :dev, but makes sense when testing code for a release (:dev to :1.0.1)
  - docker tag nfcore/bacass:dev nfcore/bacass:dev

install:
  # Install Nextflow
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Reset
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests
  # Install markdownlint-cli
  - sudo apt-get install npm && npm install -g markdownlint-cli

script:
  - nextflow run ${TRAVIS_BUILD_DIR} -profile ${SUITE},docker ${FLAGS}
