# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-bacass-1.1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - fastqc=0.11.8
  - multiqc=1.7
  - unicycler=0.4.7
  - skewer=0.2.2
  - kraken2=2.0.8_beta
  - prokka=1.13.7
  - bandage=0.8.1
  # for markdown_to_html.r
  - r-markdown=0.9
  # Nanopore analysis stuff
  - nanopolish=0.11.1
  - miniasm=0.3_r179
  - racon=1.3.2
  - canu=1.8
  - minimap2=2.17
  - samtools=1.9
  - nanoplot=1.23.1
  - pycoqc=2.2.3
  - h5py=2.9.0 #until the pycoqc recipe has been updated
  - tqdm
  - jinja2
  - plotly
