# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-bacass-1.1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.3
  - fastqc=0.11.8
  - multiqc=1.7
  - unicycler=0.4.4 #Needs to stay like this, 0.4.7 release broken on bioconda with random segfaults
  - skewer=0.2.2
  - kraken2=2.0.8_beta
  - prokka=1.14.0
  - bandage=0.8.1
  # for markdown_to_html.r
  - r-markdown=1.1
  # Nanopore analysis stuff
  - nanopolish=0.11.1
  - conda-forge::parallel=20190922
  - miniasm=0.3_r179
  - racon=1.4.7
  - canu=1.8
  - minimap2=2.17
  - samtools=1.9
  - nanoplot=1.27.0
  - pycoqc=2.5.0
  - h5py=2.9.0 #until the pycoqc recipe has been updated
